//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gen_Usuario()
        {
            this.Com_DetallesCandados = new HashSet<Com_DetallesCandados>();
            this.Com_Diesel = new HashSet<Com_Diesel>();
            this.Com_Gasolina = new HashSet<Com_Gasolina>();
            this.Uni_Unidad = new HashSet<Uni_Unidad>();
        }
    
        public int OID { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> NumEmpleado { get; set; }
        public Nullable<int> IDCard { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> EsAdministrativo { get; set; }
        public string Constraseña { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Patron { get; set; }
        public string AvisarA { get; set; }
        public string TelAvisarA { get; set; }
        public string TipoSangre { get; set; }
        public Nullable<int> Puesto { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Imagen { get; set; }
        public string IMSS { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string Modulos { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Com_DetallesCandados> Com_DetallesCandados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Com_Diesel> Com_Diesel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Com_Gasolina> Com_Gasolina { get; set; }
        public virtual gen_Puesto gen_Puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uni_Unidad> Uni_Unidad { get; set; }
    }
}
