//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uni_Unidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uni_Unidad()
        {
            this.Com_DetallesCandados = new HashSet<Com_DetallesCandados>();
            this.Com_Diesel = new HashSet<Com_Diesel>();
            this.Com_Gasolina = new HashSet<Com_Gasolina>();
        }
    
        public int OID { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoUnidad { get; set; }
        public string Millas { get; set; }
        public Nullable<int> Combustible { get; set; }
        public string Motor { get; set; }
        public Nullable<int> Cilindros { get; set; }
        public Nullable<int> Transmision { get; set; }
        public Nullable<int> Frenos { get; set; }
        public Nullable<bool> AireAcondicionado { get; set; }
        public Nullable<int> Suspencion { get; set; }
        public Nullable<bool> TieneRadio { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string Placas { get; set; }
        public string Modelo { get; set; }
        public string VIN { get; set; }
        public string Baterias { get; set; }
        public Nullable<int> Asientos { get; set; }
        public Nullable<int> Pasajeros { get; set; }
        public Nullable<int> Abanicos { get; set; }
        public Nullable<int> VentanasLaterales { get; set; }
        public Nullable<bool> TieneEstereo { get; set; }
        public Nullable<bool> TieneBocinas { get; set; }
        public Nullable<bool> TieneCamaras { get; set; }
        public Nullable<int> Puerta { get; set; }
        public Nullable<bool> TieneExtinguidor { get; set; }
        public Nullable<bool> TieneTrancas { get; set; }
        public string FiltroAceiteMotor { get; set; }
        public string FiltroCombustible { get; set; }
        public string FiltroAceiteTransmision { get; set; }
        public string FiltroAire { get; set; }
        public string FiltroAgua { get; set; }
        public Nullable<int> Imagen { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<System.DateTime> UltimoCambioAceite { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> LlantaFrontalIzquierdaChofer { get; set; }
        public Nullable<int> LlantaFrontalDerechaEstribo { get; set; }
        public Nullable<int> LlantaTraseraInteriorChofer { get; set; }
        public Nullable<int> LlantaTraseraInteriorEstribo { get; set; }
        public Nullable<int> LlantaTraseraExteriorChofer { get; set; }
        public Nullable<int> LlantaTraseraExteriorEstribo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Com_DetallesCandados> Com_DetallesCandados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Com_Diesel> Com_Diesel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Com_Gasolina> Com_Gasolina { get; set; }
        public virtual gen_Usuario gen_Usuario { get; set; }
    }
}
