<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AnunciosUsuarios.aspx.cs" Inherits="ATRCWEB.AnunciosUsuarios" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" style=" height:100%; margin:0;">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body style=" height:100%; margin:0;">
    <form id="form1" runat="server" style=" height:100%; margin:0;">
        <dx:ASPxTimer ID="ASPxTimer1" runat="server" Interval="50000">
            <ClientSideEvents Tick="function(s,e){CallBackValidar.PerformCallback();}" />
        </dx:ASPxTimer>
        <dx:ASPxCallbackPanel ID="CallBackValidar" ClientInstanceName="CallBackValidar" OnCallback="CallBackValidar_Callback" runat="server" Width="200px">
            <SettingsLoadingPanel Enabled="false" />
            <ClientSideEvents EndCallback="function (s,e){ if(CallBackValidar.cpAnunciosActualizar === 'SI'){pnlActualizar.PerformCallback();}}" />        
        </dx:ASPxCallbackPanel>

        <dx:BootstrapCallbackPanel runat="server" ClientInstanceName="pnlActualizar" ID="pnlActualizar" Height="100%" Width="100%" OnCallback="pnlActualizar_Callback">
            <SettingsLoadingPanel Enabled="false" />
            <ContentCollection>
                <dx:ContentControl>
                    <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" Height="100%" Width="100%" BackColor="White" Styles-Dot-BackColor="White" Styles-ImageArea-BackColor="White" Styles-Item-BackColor="White"
                 EnableViewState="False" EnableTheming="False" ImageContentBytesField="Anuncio">
                <SettingsImageArea AnimationType="Fade" EnableLoopNavigation="True" ImageSizeMode="ActualSizeOrFit" NavigationButtonVisibility="None"/>
                <SettingsSlideShow AutoPlay="true" StopPlayingWhenPaging="false" PausePlayingWhenMouseOver="false" PlayPauseButtonVisibility="Faded" />
                <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
            </dx:ASPxImageSlider>
                </dx:ContentControl>
            </ContentCollection>

        </dx:BootstrapCallbackPanel>
    </form>
</body>
</html>
